<?php
/** @var $block  \Perspective\TutorialEntity\Block\EntityRepository */
?>
<?php $product = $block->getProductById('1'); ?>
<?php if (!is_null($product)) : ?>
    <h2><?= $product->getName(); ?></h2>
<p><?= $product->getDescription() ?></p>
<?php endif; ?>
<hr>
<?php foreach ($block->getCheapProducts(50) as $cheapProduct): ?>
    <h2><?= $cheapProduct->getName(); ?></h2>
    <h3><?= $cheapProduct->getPrice(); ?></h3>
<?php endforeach; ?>


